# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hxh5OmqhkwWKOjztsJ_2g0vNujqT9M-
"""



from google.colab import files
uploaded = files.upload()

